AWSTemplateFormatVersion: 2010-09-09
Description: Full Stack Deployment – EC2, RDS, Lambda, Autoscaling

Parameters:
  VpcId:
    Type: String
  PublicSubnet1:
    Type: String
  PublicSubnet2:
    Type: String
  PrivateSubnet1:
    Type: String
  PrivateSubnet2:
    Type: String
  WebSG:
    Type: String
  DBSG:
    Type: String
  KeyName:
    Type: String
    Description: EC2 Key Pair Name


Resources:

  #############################################
  # EC2 INSTANCE (Main Server)
  #############################################
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0c02fb55956c7d316   # Amazon Linux 2
      KeyName: !Ref KeyName
      SubnetId: !Ref PublicSubnet1
      SecurityGroupIds:
        - !Ref WebSG
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          yum install -y httpd
          systemctl enable httpd
          systemctl start httpd
          echo "<h1>Welcome to EC2 Web App Deployed via CloudFormation</h1>" > /var/www/html/index.html



  #############################################
  # RDS SUBNET GROUP
  #############################################
  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      SubnetIds:
        - !Ref PrivateSubnet1
        - !Ref PrivateSubnet2


  #############################################
  # RDS DATABASE INSTANCE
  #############################################
  RDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: mysql
      EngineVersion: "8.0"
      DBName: appdb
      MasterUsername: admin
      MasterUserPassword: Password123!
      VPCSecurityGroups:
        - !Ref DBSG
      PubliclyAccessible: false
      DBSubnetGroupName: !Ref DBSubnetGroup



  #############################################
  # IAM ROLE FOR LAMBDA
  #############################################
  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaBasicExecution
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"



  #############################################
  # LAMBDA FUNCTION
  #############################################
  SimpleLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.lambda_handler
      Runtime: python3.9
      Role: !GetAtt LambdaRole.Arn
      Code:
        ZipFile: |
          import json
          def lambda_handler(event, context):
              print("Lambda triggered successfully!")
              return {"statusCode": 200, "body": "Lambda executed"}



  #############################################
  # LAUNCH TEMPLATE FOR AUTOSCALING
  #############################################
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: EC2AutoScaleTemplate
      LaunchTemplateData:
        ImageId: ami-0c02fb55956c7d316
        InstanceType: t3.micro
        KeyName: !Ref KeyName
        SecurityGroupIds:
          - !Ref WebSG
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            yum update -y
            yum install -y httpd
            systemctl enable httpd
            systemctl start httpd
            echo "<h1>Auto Scaled Instance</h1>" > /var/www/html/index.html



  #############################################
  # AUTO SCALING GROUP (ASG)
  #############################################
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
        - !Ref PublicSubnet1
        - !Ref PublicSubnet2
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: "1"
      MaxSize: "4"
      DesiredCapacity: "2"
      HealthCheckType: EC2
      HealthCheckGracePeriod: 60



  #############################################
  # AUTO SCALING TARGET TRACKING POLICY
  #############################################
  CPUAutoScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 50



Outputs:

  EC2InstanceId:
    Description: ID of EC2 Instance
    Value: !Ref EC2Instance

  RDSEndpoint:
    Description: RDS Endpoint
    Value: !GetAtt RDSInstance.Endpoint.Address

  LambdaFunctionName:
    Description: Lambda Function Name
    Value: !Ref SimpleLambda

